apiVersion: apps/v1
kind: Deployment

metadata:
  name: gpu-app-node-anti-affinity
  namespace: default

spec:
  replicas: 2

  selector:
    matchLabels:
      app: gpu-app-node-anti-affinity

  template:
    metadata:
      labels:
        app: gpu-app-node-anti-affinity

    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gpu
                operator: NotIn
                values:
                - "true"

      containers:
      - name: gpu-container
        image: nginx:1.28

        ports:
        - containerPort: 80
