apiVersion: apps/v1
kind: Deployment

metadata:
  name: gpu-app-node-selector
  namespace: default

spec:
  replicas: 2

  selector:
    matchLabels:
      app: gpu-app-node-selector

  template:
    metadata:
      labels:
        app: gpu-app-node-selector

    spec:
      nodeSelector:
        gpu: "true"

      containers:
      - name: gpu-nginx
        image: nginx:1.28
